<a href="https://colab.research.google.com/github/nguyenanhtienabcd/AIO2024_EXERCISE/blob/feature%2FMODULE5-WEEK4/m05w04_ex4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ex4: Adam

cho một hàm số Loss ban đầu như dưới đây:
$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$ \\
Giá trị khởi tạo:
$$w1 = -5,\; w2 = -2,\; s1 = 0,\; s2 = 0,\; v_1 = 0,\; v_2 = 0\; α = 0.2,\; \beta_1 = 0.9,\; \beta_2 = 0.999,\; \epsilon = 10^{-6} $$ \\


**Epoch1**:

- **STEP1**: tính đạo hàm riêng cho hàm số \\
$$
\begin{aligned}
{f_{w_1}}^{'} = \frac{\partial f}{\partial w_1} & = 2 \cdot 0.1w_1 = 0.2w_1 = -1  \\
{f_{w_2}}^{'} = \frac{\partial f}{\partial w_2} & = 2 \cdot 2w_2 = 4w_2 = -8
\end{aligned}
$$

- **STEP2**: cập nhật biến số của hàm v \\
$$
\begin{aligned}
v_1^1 &= \beta_1 \cdot v_1^1 + (1-\beta_1) \cdot \frac{\partial f}{\partial w_1}  = 0.9 \cdot 0 + 0.1\cdot (-1) = -0.1  \\
v_2^1 &= \beta_1 \cdot v_2^1 + (1-\beta_1) \cdot \frac{\partial f}{\partial w_2}  = 0.9 \cdot 0 + 0.1 \cdot (-8) = -0.8
\end{aligned}
$$

- **STEP3**: cập nhật biến số của hàm s \\
$$
\begin{aligned}
s_1^1 &= \beta_2 \cdot s_1 + (1-\beta_2) \cdot ({f_{w_1}}^{'})^2 = 0.999 \cdot 0  + 0.001 \cdot (-1)^2 = 0.001 \\
s_2^1 &= \beta_2 \cdot s_2 + (1-\beta_2) \cdot ({f_{w_2}}^{'})^2 = 0.999 \cdot 0 + 0.001 \cdot (-8)^2 = 0.064
\end{aligned}
$$

- **STEP4**: tính toán bias-correction \\
$$
\begin{aligned}
v_{1corr} &= \frac{v_1^1}{1-({\beta_1})^1} = \frac{-0.1}{1-0.9} = -1\\
v_{2corr} &= \frac{v_2^1}{1-({\beta_1})^1} = \frac{-0.8}{1-0.9} = -8\\
s_{1corr} &= \frac{s_1^1}{1-({\beta_1})^1} = \frac{0.001}{1-0.999} = 1\\
s_{2corr} &= \frac{s_2^1}{1-({\beta_1})^1} = \frac{0.064}{1-0.999} = 64\\
\end{aligned}
$$

- **STEP5**: cập nhật trọng số w \\
$$
\begin{aligned}
w_1^2 = w_1^1 - \alpha \cdot \frac{v_{1\text{corr}}}{\sqrt[2]{s_{1\text{corr}}} + \epsilon} = -5 - 0.2 \cdot \frac{-1}{\sqrt[2]{1} + 10^{-6}} = -5 + 0.2 = -4.8
\\
w_2^2 = w_2^1 - \alpha \cdot \frac{v_{2\text{corr}}}{\sqrt[2]{s_{2\text{corr}}} + \epsilon} = -2 - 0.2 \cdot \frac{-8}{\sqrt[2]{64} + 10^{-6}} = -2 + 0.2 = -1.8 \\
\end{aligned}
$$


**Epoch 2**:

- **STEP1**: tính đạo hàm riêng cho hàm số \\
$$
\begin{aligned}
{f_{w_1}}^{'} = \frac{\partial f}{\partial w_1} & = 2 \cdot 0.1w_1 = 0.2w_1 = 0.2 \cdot (-4.8) = -0.96 \\
{f_{w_2}}^{'} = \frac{\partial f}{\partial w_2} & = 2 \cdot 2w_2 = 4w_2 = 4 \cdot (-1.8) = -7.2
\end{aligned}
$$

- **STEP2**: cập nhật biến số của hàm v \\
$$
\begin{aligned}
v_1^2 &= \beta_1 \cdot v_1^1 + (1-\beta_1) \cdot \frac{\partial f}{\partial w_1} = 0.9 \cdot (-0.1) + 0.1 \cdot (-0.96) = -0.186 \\
v_2^2 &= \beta_1 \cdot v_2^1 + (1-\beta_1) \cdot \frac{\partial f}{\partial w_2} = 0.9 \cdot (-0.8) + 0.1 \cdot (-7.2) = -1.44
\end{aligned}
$$

- **STEP3**: cập nhật biến số của hàm s \\
$$
\begin{aligned}
s_1^2 &= \beta_2 \cdot s_1^1 + (1-\beta_2) \cdot ({f_{w_1}}^{'})^2 = 0.999 \cdot 0.001 + 0.001 \cdot (-0.96)^2 = 0.00191904 \\
s_2^2 &= \beta_2 \cdot s_2^1 + (1-\beta_2) \cdot ({f_{w_2}}^{'})^2 = 0.999 \cdot 0.064 + 0.001 \cdot (-7.2)^2 = 0.0698624
\end{aligned}
$$

- **STEP4**: tính toán bias-correction \\
$$
\begin{aligned}
v_{1corr} &= \frac{v_1^2}{1-({\beta_1})^2} = \frac{-0.186}{1-0.9^2} = \frac{-0.186}{0.19} = -0.9789 \\
v_{2corr} &= \frac{v_2^2}{1-({\beta_1})^2} = \frac{-1.44}{1-0.9^2} = \frac{-1.44}{0.19} = -7.5789 \\
s_{1corr} &= \frac{s_1^2}{1-({\beta_2})^2} = \frac{0.00191904}{1-0.999^2} = \frac{0.00191904}{0.001999} = 0.9597 \\
s_{2corr} &= \frac{s_2^2}{1-({\beta_2})^2} = \frac{0.0698624}{1-0.999^2} = \frac{0.0698624}{0.001999} = 34.9545
\end{aligned}
$$

- **STEP5**: cập nhật trọng số w \\
$$
\begin{aligned}
w_1^3 &= w_1^2 - \alpha \cdot \frac{v_{1corr}}{\sqrt[2]{s_{1corr}} + \epsilon} = -4.8 - 0.2 \cdot \frac{-0.9789}{\sqrt[2]{0.9597} + 10^{-6}}
= -4.8 + 0.2 \cdot 0.9989 = -4.8 + 0.1998 = -4.6002 \\
w_2^3 &= w_2^2 - \alpha \cdot \frac{v_{2corr}}{\sqrt[2]{s_{2corr}} + \epsilon} = -1.8 - 0.2 \cdot \frac{-7.5789}{\sqrt[2]{34.9545} + 10^{-6}}
= -1.8 + 0.2 \cdot 1.284 = -1.8 + 0.2568 = -1.5432
\end{aligned}
$$

In [1]:
import numpy as np

In [2]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    W = np.asarray(W)
    dW = np.array([0.2, 4])*W
    return dW

In [3]:
def Adam(W, dW, lr, V, S, beta1 = 0.9, beta2 = 0.999, t = 1):
    """
    Thực hiện thuật tóan Adam để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    beta1 -- float: hệ số long-range average cho V
    beta2 -- float: hệ số long-range average cho S
    t -- int: lần thứ t update (bắt đầu bằng 1)
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6

    V = beta1*V + (1-beta1)*dW
    S = beta2*S + (1-beta2)*(dW**2)
    V_hat = V/(1-beta1**t)
    S_hat = S/(1-beta2**t)
    W = W - lr*V_hat/(np.sqrt(S_hat + epsilon))

    return W, V, S

In [4]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]

    for i in range(epochs):
        dW = df_w(W)
        W, V, S = optimizer(W, dW, lr, V, S, beta1 = 0.9, beta2 = 0.999, t = i+1)
        results.append(W)

    return results

In [5]:
train_p1(Adam, lr = 0.2, epochs = 30)

[array([-5., -2.], dtype=float32),
 array([-4.8000001, -1.8      ]),
 array([-4.60025458, -1.60082446]),
 array([-4.40094818, -1.40317255]),
 array([-4.20227724, -1.20787812]),
 array([-4.00444983, -1.01592732]),
 array([-3.80768579, -0.82847292]),
 array([-3.61221664, -0.64684142]),
 array([-3.41828545, -0.47252746]),
 array([-3.22614653, -0.30716913]),
 array([-3.03606497, -0.15249832]),
 array([-2.84831603, -0.01026302]),
 array([-2.66318433,  0.11787577]),
 array([-2.48096283,  0.23046186]),
 array([-2.30195156,  0.32635894]),
 array([-2.12645613,  0.40484216]),
 array([-1.95478597,  0.46564981]),
 array([-1.7872523 ,  0.50898816]),
 array([-1.62416583,  0.53549455]),
 array([-1.46583419,  0.54617153]),
 array([-1.31255919,  0.54230818]),
 array([-1.16463376,  0.52540208]),
 array([-1.02233886,  0.49709058]),
 array([-0.88594013,  0.45909505]),
 array([-0.75568468,  0.41317772]),
 array([-0.63179773,  0.36110878]),
 array([-0.51447945,  0.30464032]),
 array([-0.40390206,  0.2454839